image: "ruby:2.5"

stages:
  - deploy

before_script:
  - apt-get update -qq
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

job:
  stage: deploy
  type: deploy
  script:
    - echo "Deploying to production environment"
    - ssh trucky@ssd.bdeascii.fr -t "echo hi"
